Class {
	#name : 'SCMockClassAnotherHierarchy',
	#superclass : 'Object',
	#category : 'SendersChainTransformer-Tests-Utilities',
	#package : 'SendersChainTransformer-Tests',
	#tag : 'Utilities'
}

{ #category : 'as yet unclassified' }
SCMockClassAnotherHierarchy >> <->,/>+@<-<>@>>-+,,/<@ anObject [

   ^ 22
]

{ #category : 'as yet unclassified' }
SCMockClassAnotherHierarchy >> wEiRDFoo [

   ^ 33
]
